export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';

export const GET_LEADERBOARD_REQUEST = 'GET_LEADERBOARD_REQUEST';
export const GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS';
export const GET_LEADERBOARD_FAIL = 'GET_LEADERBOARD_FAIL';

export const EDIT_QUESTIONBYADMIN_REQUEST = 'EDIT_QUESTIONBYADMIN_REQUEST';
export const EDIT_QUESTIONBYADMIN_SUCCESS = 'EDIT_QUESTIONBYADMIN_SUCCESS';
export const EDIT_QUESTIONBYADMIN_FAIL = 'EDIT_QUESTIONBYADMIN_FAIL';
