export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_FEEDBACK_REQUEST = 'USER_FEEDBACK_REQUEST';
export const USER_FEEDBACK_SUCCESS = 'USER_FEEDBACK_SUCCESS';
export const USER_FEEDBACK_FAIL = 'USER_FEEDBACK_FAIL';

export const GET_ANSWERKEY_REQUEST = 'GET_ASNWERKEY_REQUEST';
export const GET_ANSWERKEY_SUCCESS = 'GET_ASNWERKEY_SUCCESS';
export const GET_ANSWERKEY_FAIL = 'GET_ANSWERKEY_FAIL';
