export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST';
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL';
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';

export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL';

export const EDIT_QUESTION_REQUEST = 'EDIT_QUESTION_REQUEST';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_FAIL = 'EDIT_QUESTION_FAIL';
export const EDIT_QUESTION_STOP = 'EDIT_QUESTION_FAIL';

export const TEST_QUESTIONS_REQUEST = 'TEST_QUESTIONS_REQUEST';
export const TEST_QUESTIONS_SUCCESS = 'TEST_QUESTIONS_SUCCESS';
export const TEST_QUESTIONS_FAIL = 'TEST_QUESTIONS_FAIL';
export const TEST_QUESTIONS_ANSWERED = 'TEST_QUESTIONS_ANSWERED';

export const SUBMIT_TEST_REQUEST = 'SUBMIT_TEST_REQUEST';
export const SUBMIT_TEST_SUCCESS = 'SUBMIT_TEST_SUCCESS';
export const SUBMIT_TEST_FAIL = 'SUBMIT_TEST_FAIL';

export const GET_QUESTIONBYID_REQUEST = 'GET_QUESTIONBYID_REQUEST';
export const GET_QUESTIONBYID_SUCCESS = 'GET_QUESTIONBYID_SUCCESS';
export const GET_QUESTIONBYID_FAIL = 'GET_QUESTIONBYID_FAIL';
